#!/bin/bash
displays a confused smiley
Display the content of the file
Display the content of hosts
Display the last 10 lines of passwd
Display the first 10 lines of passwd
displays the third line of the file iacta
creates a file named exactly containing the text Best School ending by a new line.
writes into the file content the result of the command
duplicates the last line of the file iacta
deletes all the regular files
counts the number of directories and sub-directories in the current directory.
displays the 10 newest files in the current directory.
takes a list of words as input and prints only words that appear exactly once.
Display lines containing the pattern “root” from the file
Display the number of lines that contain the pattern  in the file
Display lines containing the pattern  and 3 lines after them in the file
Display all the lines in the file that do not contain the pattern
Display all lines of the file starting with a letter.
Replace all characters A and c from input to Z and e respectively.
Create a script that removes all letters c and C from input.
Write a script that reverse its input.
displays all users and their home directories, sorted by users.


